baseurl = "/"
languageCode = "ja-jp"
title = ">> work.log"
theme = "hugo-cactus-theme"
disqusShortname = "worklog"
googleAnalytics = "UA-39930558-1"

[permalinks]
  post = "/entry/:year/:month/:day/:slug/"

[params]
  name = "mursts"
  description = "Describe your website"
  bio = "チラ裏です"
  # Enter optionally your twitter account
  twitter = "mursts"
  enableRSS = true

  # Disqus comment
  disqusShortname = "worklog"
  # Disable disqus comments by set `enableDisqus = "false"`
  enableDisqus = true

  # Enable googleAnalytics
  enableGoogleAnalytics = true 

  # Add custom assets with their paths relative to the static folder
  customCSS = ["css/custom.css"]
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home = "Home"
  about = "About"
  subscribe = "Rss"
  # Pagination links
  olderPosts = ""
  newerPosts = ""
  readMore = ""
  copyright = ""
  # Sharing options and author information in posts
  aboutAuthor = "Python東海 / GCPUG Nagoyaの中の人"
  tweet = ""
  share = ""
  # 404 page
  title404 = ""
  subtitle404 = ""

  # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
  iconFont = "font-awesome"
   # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "circle"

[social]
  twitter  = "https://www.twitter.com/mursts"
  github   = "https://www.github.com/mursts"
  instagram   = "https://www.instagram.com/mursts/"

