baseurl = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = ">>Work.log"
disqusShortname = "worklog"
googleAnalytics = "UA-39930558-1"
theme = "zozo"
summaryLength = 100
paginate = 5
enableEmoji = true

hasCJKLanguage = true

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[permalinks]
  post = "/entry/:year/:month/:day/:slug/"

[author]
  name = "mursts"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "チラシの裏"
  footerSlogan = ""
  keywords = ["Hugo","theme","zozo"]
  description = "Hugo theme zozo example site."
  enableMathJax = true
  enableSummary = false
  mainSections = ["posts","post"]

[outputs]
  home = ["HTML", "RSS"]

[social]
  github = "https://github.com/mursts"
  twitter = "https://twitter.com/mursts"
  instagram = "https://instagram.com/mursts"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
