baseurl = "/"
languageCode = "ja"
title = ">> work.log"
theme = "beautifulhugo"

[Indexes]
tag = "tags"

disqusShortname = "worklog"
googleAnalytics = "UA-39930558-1"

[permalinks]
    post = "/entry/:year/:month/:day/:slug/"

[Params]
#  logo = "mursts.jpg"
  subtitle = "チラ裏です"

[Author]
  name = "mursts"
#  email = "youremail@domain.com"
  facebook = "Satoshi.3URA"
  github = "mursts"
  twitter = "mursts"
#  linkedin = "pub/username/X/YYY/ZZZ"
#  stackoverflow = "XXXXXXX/username"
#  soundcloud = "username"
#  wikipedia = "username"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
