baseurl = "/"
languageCode = "ja-jp"
title = ">> work.log"
theme = "aglaus"

copyright = "Copyright (c) 2012 - 2016, mursts; all rights reserved."
canonifyurls = true
paginate = 5

[permalinks]
  post = "/entry/:year/:month/:day/:slug/"

[params]
  subtitle = "チラ裏です"
  disqusShortname = "worklog"
  toc = false
  DateForm = "2006/01/02"

  SyntaxHighlightTheme = "github.min.css"

  GoogleAnalyticsUserID = "UA-39930558-1"
