baseurl = "/"
languageCode = "ja-jp"
title = ">> work.log"
theme = "hugo-cactus-theme"
# paginate = 5
# disqusShortname = "worklog"
# googleAnalytics = "UA-39930558-1"

[permalinks]
  post = "/entry/:year/:month/:day/:slug/"

[params]
  name = "mursts"
  description = "Describe your website"
  bio = "Blogger - Programmer - Gopher"
  # Enter optionally your twitter account
  twitter = "mursts"
  enableRSS = true

  # Add custom assets with their paths relative to the static folder
  customCSS = ["/css/custom.css"]
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home = "/"
  about = "/about"
  subscribe = ""
  # Pagination links
  olderPosts = ""
  newerPosts = ""
  readMore = ""
  copyright = ""
  # Sharing options and author information in posts
  aboutAuthor = "I'm an enthusiastic gopher."
  tweet = ""
  share = ""
  # 404 page
  title404 = ""
  subtitle404 = ""

  # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
  iconFont = "mono-social"
   # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "circle"
