baseurl = "/"
languageCode = "ja-JP"
title = ">> work.log"
theme = "beautifulhugo"

[permalinks]
  post = "/entry/:year/:month/:day/:slug/"

pygmentsUseClasses = true
disqusShortname = "worklog"
googleAnalytics = "UA-39930558-1"

[Params]
  logo = ""
  subtitle = "チラ裏です"

[Author]
  name = "mursts"
  email = ""
  facebook = "Satoshi.3URA"
  github = "mursts"
  twitter = "mursts"
  linkedin = ""
  stackoverflow = ""
  soundcloud = ""
  wikipedia = ""

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
