baseurl = "http://blog.mursts.jp/"
languageCode = "ja"
title = ">> work.log"
tags = "tags"
theme = "angels-ladder"

disqusShortname = "worklog"

[permalinks]
    post = "/entry/:year/:month/:day/:slug/"

[params]
    subtitle = "チラ裏です"
    twitter = "https://twitter.com/mursts"
    github = "https://github.com/mursts"
    copyright = "Written by mursts"
    analytics = "UA-39930558-1"
    showsRSS = true


