name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '284.0.0'
        service_account_email: ${{ secrets.SA_EMAIL }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    # Configure gcloud CLI
    - name: gcloud Set up
      run: |
        echo ${{ secrets.RUN_PROJECT }} > p.txt
        cat p.txt
        echo ${{ secrets.SA_EMAIL }} > e.txt
        cat e.txt
        echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} > c.txt
        cat c.txt
        gcloud config set project ${{ secrets.RUN_PROJECT }}
        gcloud config list

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.67.0'

    - name: Build
      run: hugo --minify

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --quiet

    - name: Delete cloud build objetcts
      run: |
        gsutil -m rm -r gs://asia.artifacts.${{ secrets.RUN_PROJECT }}.appspot.com/containers/*
        gsutil -m rm -r gs://staging.${{ secrets.RUN_PROJECT }}.appspot.com/*

