name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Setup gcloud CLI
    # - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    #   with:
    #     version: '290.0.1'
    #     service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    #     export_default_credentials: true

    # Configure gcloud CLI
    # - name: gcloud Set up
    #   run: |
    #     gcloud config set project ${{ secrets.RUN_PROJECT }}

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.67.0'

    - name: Build
      run: hugo --minify

    # - name: Deploy to App Engine
    #   run: |
    #     gcloud app deploy app.yaml --quiet 

    - name: Deploy
      uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
      with:
        credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Delete cloud build objetcts
      run: |
        gsutil -m rm -r gs://asia.artifacts.${{ secrets.RUN_PROJECT }}.appspot.com/containers/*
        gsutil -m rm -r gs://staging.${{ secrets.RUN_PROJECT }}.appspot.com/*

